services:
  app1:
    build: ./server
    environment:
      - APP_NAME=App1
    ports:
      - "3001:3000"

  app2:
    build: ./server
    environment:
      - APP_NAME=App2
    ports:
      - "3002:3000"

  app3:
    build: ./server
    environment:
      - APP_NAME=App3
    ports:
      - "3003:3000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl.crt:/etc/nginx/ssl/ssl.crt
      - ./nginx/ssl.key:/etc/nginx/ssl/ssl.key
    depends_on:
      - app1
      - app2
      - app3
